import { motion } from "framer-motion";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Bell, AlertCircle, FileText, Download } from "lucide-react";
import { Badge } from "@/components/ui/badge";

export default function Notifications() {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.4 }}
      className="space-y-6 max-w-4xl mx-auto"
    >
      <div className="flex justify-between items-center gap-4">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Notifications</h1>
          <p className="text-muted-foreground mt-1">Updates on your accounts and AI insights.</p>
        </div>
        <Button variant="outline" className="hidden sm:flex">Mark all as read</Button>
      </div>

      <Card>
        <CardContent className="p-0">
          <div className="divide-y">
            {[
              {
                icon: AlertCircle,
                title: "Unusual spending detected",
                desc: "Your 'Dining Out' category is 35% higher than usual this week.",
                time: "2 hours ago",
                color: "text-yellow-500",
                bg: "bg-yellow-500/10",
                unread: true,
                action: "Review Expenses"
              },
              {
                icon: Bell,
                title: "Upcoming bill: Electric Utility",
                desc: "$95.20 is due in 3 days. Your account balance is sufficient.",
                time: "Yesterday",
                color: "text-primary",
                bg: "bg-primary/10",
                unread: true
              },
              {
                icon: FileText,
                title: "Monthly report is ready",
                desc: "Your October financial summary has been generated by FinanceAI.",
                time: "2 days ago",
                color: "text-blue-500",
                bg: "bg-blue-500/10",
                unread: false,
                action: "Download PDF"
              }
            ].map((n, i) => (
              <div key={i} className={`p-4 sm:p-6 flex gap-4 transition-colors hover:bg-muted/30 ${n.unread ? 'bg-muted/10' : ''}`}>
                <div className={`size-10 rounded-full flex items-center justify-center shrink-0 ${n.bg} ${n.color}`}>
                  <n.icon className="size-5" />
                </div>
                <div className="flex-1 space-y-1">
                  <div className="flex justify-between items-start">
                    <h3 className="font-semibold text-base">{n.title}</h3>
                    <span className="text-xs text-muted-foreground whitespace-nowrap ml-4">{n.time}</span>
                  </div>
                  <p className="text-sm text-muted-foreground leading-relaxed">{n.desc}</p>
                  
                  {n.action && (
                    <Button variant="secondary" size="sm" className="mt-3">
                      {n.action}
                    </Button>
                  )}
                </div>
                {n.unread && <div className="size-2.5 rounded-full bg-primary shrink-0 self-center" />}
              </div>
            ))}
          </div>
        </CardContent>
      </Card>
    </motion.div>
  );
}
